### PR TITLE
Update Ubuntu CXX 20 image

### PR DESCRIPTION
**Pull request by maxGimeno**
Use Eigen master in Ubuntu-GCC_master_cpp20-Release/Ubuntu-GCC_master_cpp20-Release

### CODE REVIEW

**Comment by lrineau** [comment]
https://travis-ci.com/github/CGAL/cgal-testsuite-dockerfiles/jobs/376894619#L28285
```
The job exceeded the maximum log length, and has been terminated.
```

**Comment by lrineau** [comment]
> [travis-ci.com/github/CGAL/cgal-testsuite-dockerfiles/jobs/376894619#L28285](https://travis-ci.com/github/CGAL/cgal-testsuite-dockerfiles/jobs/376894619#L28285)
> 
> ```
> The job exceeded the maximum log length, and has been terminated.
> ```

ping

**Comment by maxGimeno** [comment]
I don't know what to do. If we quiet those boost logs we'll have the message about no information received for 10 min and get terminated as well...

**Comment by lrineau** [comment]
I have artificially modified this PR (https://github.com/CGAL/cgal-testsuite-dockerfiles/pull/109#event-3708652381) so that Travis retest it with the new version of `master`.

**Comment by lrineau** [comment]
The Travis tests are fine now. I merge.

**Pull request merged**
