### PR TITLE
Add OpenGR and libpointmatcher on Ubuntu images

### PR DESCRIPTION
**Pull request by maxGimeno**

### CODE REVIEW

**Comment by lrineau** [comment]
Is this ready to be merged? The tests seem alright.

**Comment by maxGimeno** [comment]
If we merge that, every Ubuntu platform will be red for PSP_Example until my PR is merged, so I don't think it should be merged right now

**Comment by maxGimeno** [comment]
cf https://github.com/CGAL/cgal/pull/5350

**Comment by maxGimeno** [comment]
I think it can be merged now, we'll start testing the PR

**Pull request merged**
